// src/components/UploadBox.jsx
import React, { useRef, useState } from "react";
import { predictImage } from "../api";

// ====== Optional: class -> description mapping ======
const DEFECT_INFO = {
  crazing:
    "Fine surface cracks caused by thermal or mechanical stress during processing.",
  inclusion:
    "Non-metallic particles trapped in the steel during manufacturing.",
  patches:
    "Irregular surface patches due to rolling or coating inconsistencies.",
  pitted_surface:
    "Small pits/holes formed due to corrosion or process contamination.",
  rolled_in_scale:
    "Oxide scale pressed into the surface during rolling operations.",
  scratches:
    "Surface scratches caused by contact with sharp objects or rough handling.",
};

function CloudIcon() {
  return (
    <svg width="88" height="58" viewBox="0 0 88 58" fill="none">
      <path
        d="M29.5 47.5H63.8C72.0 47.5 78.5 41.3 78.5 33.6C78.5 26.5 72.9 20.6 65.3 19.9C63.1 11.5 55.3 5.5 45.9 5.5C36.2 5.5 28.2 12.0 26.3 20.9C19.2 22.1 13.8 28.0 13.8 35.0C13.8 42.1 20.1 47.5 29.5 47.5Z"
        stroke="rgba(255,255,255,0.9)"
        strokeWidth="3"
        strokeLinejoin="round"
      />
      <path
        d="M44 41V25"
        stroke="#20E3FF"
        strokeWidth="5"
        strokeLinecap="round"
      />
      <path
        d="M36.5 31.5L44 24L51.5 31.5"
        stroke="#20E3FF"
        strokeWidth="5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

export default function UploadBox() {
  const inputRef = useRef(null);

  // stages: upload -> preview -> result
  const [stage, setStage] = useState("upload");

  const [dragOver, setDragOver] = useState(false);

  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null); // {prediction, confidence, filename} OR {error}

  function resetAll() {
    setStage("upload");
    setDragOver(false);
    setFile(null);
    setPreviewUrl("");
    setLoading(false);
    setResult(null);
    if (inputRef.current) inputRef.current.value = "";
  }

  function pickFile(f) {
    if (!f) return;
    setFile(f);
    setPreviewUrl(URL.createObjectURL(f));
    setResult(null);
    setLoading(false);
    setStage("preview");
  }

  async function onDetect() {
    if (!file) return;
    setLoading(true);
    setResult(null);

    try {
      const data = await predictImage(file); // expects {prediction, confidence, filename}
      setResult(data);
      setStage("result"); // ✅ IMPORTANT: go to result page after detect
    } catch (e) {
      setResult({ error: e?.message || "Prediction failed" });
      // stay on preview so user can retry
      setStage("preview");
    } finally {
      setLoading(false);
    }
  }

  function onDrop(e) {
    e.preventDefault();
    setDragOver(false);
    const f = e.dataTransfer.files?.[0];
    pickFile(f);
  }

  // ====== RENDER: RESULT SCREEN (the page you want after Detect Defect) ======
  if (stage === "result" && result?.prediction) {
    const predRaw = String(result.prediction || "").toLowerCase();
    const predTitle = predRaw
      .split("_")
      .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
      .join(" ");

    return (
      <div className="upload-stage">
        <div className="above-title">Analysis Result</div>

        <div className="upload-panel">
          <div className="result-box">
            <div className="result-head">Result</div>

            <div className="result-pill">
              Defect Type :- <span className="result-strong">{predTitle}</span>
            </div>

            <div className="result-desc">
              Description :-{" "}
              {DEFECT_INFO[predRaw] ||
                "Prediction generated by trained CNN model based on visual patterns."}
            </div>

            {typeof result.confidence === "number" && (
              <div className="result-conf">
                Confidence :- {(result.confidence * 100).toFixed(2)}%
              </div>
            )}
          </div>

          <button className="big-btn" type="button" onClick={resetAll}>
            Add another image
          </button>
        </div>

        <p className="footer-note">
          This prediction is generated by a trained CNN model based on visual
          <br />
          surface patterns.
        </p>

        <input ref={inputRef} type="file" accept="image/*" hidden />
      </div>
    );
  }

  // ====== RENDER: PREVIEW SCREEN ======
  if (stage === "preview" && file) {
    return (
      <div className="upload-stage">
        <div className="upload-panel">
          <div className="panel-title">Image Preview</div>

          <div className="preview-zone">
            <div className="preview-dots">
              <div className="preview-frame">
                {previewUrl ? (
                  <img className="preview-img" src={previewUrl} alt="preview" />
                ) : null}
              </div>

              <button
                className="detect-btn"
                type="button"
                onClick={onDetect}
                disabled={loading}
              >
                {loading ? "Detecting..." : "Detect Defect"}
              </button>
            </div>
          </div>
        </div>

        <p className="helper">
          Review the uploaded image and click <b>Detect Defect</b> to analyze it.
        </p>


        {!loading && result?.error && (
          <div className="result-strip">
            <span className="err">{result.error}</span>
          </div>
        )}

        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          hidden
          onChange={(e) => pickFile(e.target.files?.[0])}
        />
      </div>
    );
  }

  // ====== RENDER: UPLOAD SCREEN ======
  return (
    <div className="upload-stage">
      <div className="upload-panel">
        <div
          className={`dropzone-dark ${dragOver ? "drag" : ""}`}
          onDragOver={(e) => {
            e.preventDefault();
            setDragOver(true);
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={onDrop}
        >
          <div className="dropzone-dots">
            <div className="cloud-wrap">
              <CloudIcon />
            </div>

            <div className="drop-title">Drag &amp; Drop the Image Here</div>

            <button
              className="upload-btn"
              type="button"
              onClick={() => inputRef.current?.click()}
            >
              or click to upload
            </button>

            <input
              ref={inputRef}
              type="file"
              accept="image/*"
              hidden
              onChange={(e) => pickFile(e.target.files?.[0])}
            />
          </div>
        </div>
      </div>
      <p className="helper">
          Upload a clear steel surface image to identify
          <br />
          potential manufacturing defects using an AI model.
          <br />
          Supported formats: JPG, PNG
        </p>
    </div>
  );
}
